### ISSUE TITLE
not able to compile on ubuntu20.04/1804

### ISSUE THREAD

**Issue by nikhilagarwal-xlnx** [nhorman/dropwatch#51]
getting following error while make 
up_kas.o lookup_bfd.o  -lnl-genl-3 -lnl-3 -lbfd -lpcap
main.o: In function `enter_command_line_mode':
/group/cdc_hd/members/nagarwal/x3/dropwatch/src/main.c:865: undefined reference to `readline'
collect2: error: ld returned 1 exit status
Makefile:389: recipe for target 'dropwatch' failed
make[2]: *** [dropwatch] Error 1
make[2]: Leaving directory '/group/cdc_hd/members/nagarwal/x3/dropwatch/src'
Makefile:402: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/group/cdc_hd/members/nagarwal/x3/dropwatch'
Makefile:333: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nhorman** [comment]
what version of dropwatch are you trying to build? If you're not building the head of the tree, dropwatch silently assumes that you have the readline development libraries and headers installed due to the lack of a pkg-config file (see commit c18f3d25a94eb72145c663797794d2697a226594).  If you're building after that commit, the configure stage will fail with an appropriate error message telling you what you need

In either case, the fix is simple, install the libreadline devel headers on your system prior to config/building of dropwatch

**Comment by nikhilagarwal-xlnx** [comment]
i am using master branch top of the tree code, i have also installed  libreadline devel and  libreadline common packages.
Issue i see is there is no  libreadline binary on my system and there is no package for that in ubuntu 20.04. Can you point to any specific package that you want me to install and try?

**Comment by nhorman** [comment]
hmm, that doesn't make any sense.  According to this:
https://packages.ubuntu.com/focal/amd64/libreadline-dev/filelist
libreadline-dev should have the pkg-config file included, so your configure script should pass muster

And from this:
https://packages.ubuntu.com/focal/libs/libreadline8

That should be all the libraries you need.  Did you install libreadline8?  I do note that there is a libreadline package in ubuntu, and I'm not sure what the difference is.

**Comment by nikhilagarwal-xlnx** [comment]
both of these packages are installed and all these headers are present on my system.

**Comment by nhorman** [comment]
please upload the output of your configure script and the entire compilation output here

**Comment by nikhilagarwal-xlnx** [comment]
/<3>nagarwal/x3/dropwatch>>./autogen.sh
+ mkdir -p m4
+ autoreconf -fv --install
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:9: installing './compile'
configure.ac:8: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
/<3>nagarwal/x3/dropwatch>>./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gawk... (cached) gawk
checking for getopt_long... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for LIBPCAP... no
checking for pcap_open_live in -lpcap... yes
checking bfd.h usability... yes
checking bfd.h presence... yes
checking for bfd.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure:
configure: dropwatch Version:     1.5.3
configure: Target:
configure: Installation prefix:    /usr/local
configure: Compiler:               gcc
configure: Compiler flags: -g -O2
configure: BFD library support: yes
/<3>nagarwal/x3/dropwatch>>make
make  all-recursive
make[1]: Entering directory '/group/cdc_hd/members/nagarwal/x3/dropwatch'
Making all in src
make[2]: Entering directory '/group/cdc_hd/members/nagarwal/x3/dropwatch/src'
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lookup.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -MT lookup.o -MD -MP -MF $depbase.Tpo -c -o lookup.o lookup.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lookup_kas.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -MT lookup_kas.o -MD -MP -MF $depbase.Tpo -c -o lookup_kas.o lookup_kas.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lookup_bfd.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE  -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -MT lookup_bfd.o -MD -MP -MF $depbase.Tpo -c -o lookup_bfd.o lookup_bfd.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -lnl-3 -lnl-genl-3 -lnl-3  -lpcap -lbfd  -o dropwatch main.o lookup.o lookup_kas.o lookup_bfd.o  -lpcap
libtool: link: gcc -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3 -g -O2 -o dropwatch main.o lookup.o lookup_kas.o lookup_bfd.o  -lnl-genl-3 -lnl-3 -lbfd -lpcap
main.o: In function `enter_command_line_mode':
/group/cdc_hd/members/nagarwal/x3/dropwatch/src/main.c:865: undefined reference to `readline'
collect2: error: ld returned 1 exit status
Makefile:400: recipe for target 'dropwatch' failed
make[2]: *** [dropwatch] Error 1
make[2]: Leaving directory '/group/cdc_hd/members/nagarwal/x3/dropwatch/src'
Makefile:413: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/group/cdc_hd/members/nagarwal/x3/dropwatch'
Makefile:345: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nhorman** [comment]
well, that explains it.  You said that you're running from the head of the master branch of dropwatch, but you're not.  From your config output above:

checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for LIBPCAP... no
checking for pcap_open_live in -lpcap... yes

We're checking for various libraries there, but in the most recent [configure.ac](https://github.com/nhorman/dropwatch/blob/master/configure.ac), we have this:
PKG_CHECK_MODULES([READLINE], [readline], [], [AC_MSG_ERROR([libreadline is required])])

Which should print this, as it does on my freshly cloned tree:
checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for READLINE... yes    <======HERE
checking for LIBPCAP... yes

Because you don't have a configure.ac that runs that check, you're not setting READLINE_LIBS and READLINE_CFLAGS properly, and when you compile you can't find the headers you need.

**Comment by nikhilagarwal-xlnx** [comment]
again pulled in latest there was on only a readme patch on mater. Still the same.

**Comment by nikhilagarwal-xlnx** [comment]
/<3>nagarwal/x3/dropwatch>>./autogen.sh
+ mkdir -p m4
+ autoreconf -fv --install
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:9: installing './compile'
configure.ac:8: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
/<3>nagarwal/x3/dropwatch>>./co
compile*       config.guess*  config.status* config.sub*    configure*
/<3>nagarwal/x3/dropwatch>>./con
config.guess*  config.status* config.sub*    configure*
/<3>nagarwal/x3/dropwatch>>./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gawk... (cached) gawk
checking for getopt_long... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for LIBPCAP... no
checking for pcap_open_live in -lpcap... yes
checking bfd.h usability... yes
checking bfd.h presence... yes
checking for bfd.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
configure:
configure: dropwatch Version:     1.5.3
configure: Target:
configure: Installation prefix:    /usr/local
configure: Compiler:               gcc
configure: Compiler flags: -g -O2
configure: BFD library support: yes
/<3>nagarwal/x3/dropwatch>>make
make  all-recursive
make[1]: Entering directory '/group/cdc_hd/members/nagarwal/x3/dropwatch'
Making all in src
make[2]: Entering directory '/group/cdc_hd/members/nagarwal/x3/dropwatch/src'
/bin/sh ../libtool  --tag=CC   --mode=link gcc -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3  -g -O2 -lnl-3 -lnl-genl-3 -lnl-3  -lpcap -lbfd  -o dropwatch main.o lookup.o lookup_kas.o lookup_bfd.o  -lpcap
libtool: link: gcc -g -Wall -Werror -I/usr/include/libnl3 -I/usr/include/libnl3 -g -O2 -o dropwatch main.o lookup.o lookup_kas.o lookup_bfd.o  -lnl-genl-3 -lnl-3 -lbfd -lpcap
main.o: In function `enter_command_line_mode':
/group/cdc_hd/members/nagarwal/x3/dropwatch/src/main.c:865: undefined reference to `readline'
collect2: error: ld returned 1 exit status
Makefile:400: recipe for target 'dropwatch' failed
make[2]: *** [dropwatch] Error 1
make[2]: Leaving directory '/group/cdc_hd/members/nagarwal/x3/dropwatch/src'
Makefile:413: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/group/cdc_hd/members/nagarwal/x3/dropwatch'
Makefile:345: recipe for target 'all' failed
make: *** [all] Error 2
/<3>nagarwal/x3/dropwatch>>git log
commit 1a3ab52332d347505e339f1d4b6537abb1ada244 (HEAD -> master, origin/master, origin/HEAD)
Author: Neil Horman <nhorman@tuxdriver.com>
Date:   Mon Jul 26 16:20:17 2021 -0400

    Update README.md

    fixing a few typos

commit ab2965faeeb63fb22b938cc4c80a417b3bf7716b
Author: Neil Horman <nhorman@gmail.com>
Date:   Wed Jul 7 08:36:48 2021 -0400

    Fix license specifiers

    It was noted that there was an LGPL license in a makefile, which is
    rather non-sensical in my mind, and clearly erroneous.  So lets fix up
    the other build files to match the spdx header in the source code

    Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

commit 643cabea308fe24e1b5f20b0f86fe4682f72d475
Merge: 0b554ed 6259779
Author: Neil Horman <nhorman@tuxdriver.com>
Date:   Tue Jul 6 07:33:52 2021 -0400

    Merge pull request #49 from liuhangbin/config

    configure: update obsoleted m4 macros

commit 6259779e26c928d59b7aae66273da095fcfcb49b

**Comment by nhorman** [comment]
Then I'm not at all sure what to tell you.  It does appear that you have the latest tree there, but clearly something is going wrong with your configure script.  With that version, if you look at configure.ac, you should see this line:
PKG_CHECK_MODULES([READLINE], [readline], [], [AC_MSG_ERROR([libreadline is required])])

but its not getting executed, as theres nothing in the configure output about it.  There might be some relevant information in your configure.log output that explains whats going on.  If you upload it here, I might be able to give you a hint

**Comment by nikhilagarwal-xlnx** [comment]
Yes i think it is issue on my end, i asked someone to look at it and in my configure script those checking was commented so was not getting error in configure. Now got error in configure itself.
```
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for READLINE... no
configure: error: libreadline is required
```

But i am able to find which exact package it needs, as i have installed all libreadline package in ubuntu can you point me to it? following is the snapshot
```
/<3>nagarwal/x3/dropwatch>>sudo apt search libreadline
Sorting... Done
Full Text Search... Done
cupt/bionic 2.10.0 amd64
  flexible package manager -- console interface

libreadline-dev/bionic,now 7.0-3 amd64 [installed]
  GNU readline and history libraries, development files

libreadline-gplv2-dev/bionic 5.2+dfsg-3build1 amd64
  GNU readline and history libraries, development files

libreadline-java/bionic,now 0.8.0.1+dfsg-6 amd64 [installed]
  GNU readline and BSD editline wrappers for Java

libreadline-java-doc/bionic,bionic 0.8.0.1+dfsg-6 all
  API docs for readline/editline wrappers for Java

libreadline5/bionic,now 5.2+dfsg-3build1 amd64 [installed]
  GNU readline and history libraries, run-time libraries

libreadline5-dbg/bionic 5.2+dfsg-3build1 amd64
  GNU readline and history libraries, debugging libraries

libreadline7/bionic,now 7.0-3 amd64 [installed]
  GNU readline and history libraries, run-time libraries

libreadline7-dbg/bionic,now 7.0-3 amd64 [installed]
  GNU readline and history libraries, debugging libraries

```

**Comment by nhorman** [comment]
um, what?  Can you elaborate on what you mean by "in my configure script those checking was commented".  Did you manually alter the configure script?  If so, why didn't you say something initially?

And the above packages all come from bionic, but the title of this bug says you're using focal (20.04).   None of those readline packages are going to give you what you need because they are older than libreadline8 and are missing the pkg-config file that I expressly told you about in the first comment of this issue

**Comment by dwdixon** [comment]
FWIW, I just learned about this awesome project last night, but I also seem to be running into issues with building on Ubuntu 18.04 related to libreadline, it's installed along with libreadline-dev but for some reason the configure script isn't recognizing that it's there.

It would be very helpful if there were a list of package dependencies required to build the binaries added to the readme for both Fedora-based distro's and Debian-based distros so one could just install them all before attempting to build.  That said, I'm not sure why it's not recognizing that libreadline is already installed but I haven't had the chance to spend a lot of time looking into it yet.

```
dropwatch$ sudo apt-get install libreadline7
Reading package lists... Done
Building dependency tree
Reading state information... Done
libreadline7 is already the newest version (7.0-3).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.

dropwatch$ sudo apt-get install libreadline-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libreadline-dev is already the newest version (7.0-3).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
```

```
checking for LIBNL3... yes
checking for LIBNLG3... yes
checking for READLINE... no
configure: error: libreadline is required
```

**Comment by nhorman** [comment]
Regarding the package dependencies, thats what the configure script is for.  It explicitly tells you when you're missing a package prior to building, just as you see above, once you un-commented the lines from the configure.ac script to check for readline (which I assume is what you did).  As for mapping library names to distribution package names, thats a task up to each individual distribution.  Easiest way to find that is to go get the packaging sources for your distro of choice (i.e. the rpm .spec file, or the debian/control file), and look at that to see what dependencies they list when they build.

As for why its not finding your package, I explained that in my first comment, and in commit c18f3d2. From the commit changelog:
Update configure to fail if readline isn't installed
    
    We had libreadline pkg check in configure hacked a bit.  Because
    libreadline didn't have a .pc file for years, we fell back on just
    adding the library as a linker option and letting the compile fail when
    readline.h couldn't be found.  Now that readline 8.0 has been out for 2
    years (which included the .pc file), I think we can safely test for it,
    and fail if its not found
    
    Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Because prior to libreadline version 8, it had no pc file (a pkg-config file), the dropwatch configure script was unable to find the library, even if it was installed properly.  Prior to commit c18f3d2, dropwatch just assumed that it was there, which got you past the configure stage, but failed during the build if you didn't have it installed (which is a worse problem).  Since libreadline 8.0 has been out for over 2 years now, we fixed up the configure script to do proper detection on the library.  In Bionic (ubuntu 18.04), its just not available, and you need to go open an issue with canonical to fix that.  Looking here:
https://packages.ubuntu.com/focal/amd64/libreadline-dev/filelist
It appears that Focal, has the latest pc file, and so if that pc file exists on your system, you should be ok.

As to what to do about all of this, you have a few options:
For Bionic, you can:

- install libreadline8, libreadline-dev, and build from the head of the tree
- just install the dropwatch deb file that they publish here (https://packages.ubuntu.com/source/focal/dropwatch).  Its a little backlevel, but not too bad

For Focal, you can:
- checkout dropwatch at a commit prior to c18f3d2, where the proper readline check doesn't exist (it just assumes its installed), and build for that.  You miss out on the subsequent bug fixes, but it works.  Note installing the deb isn't an option here, as ubuntu never built dropwatch for Focal, as far as I can tell.

**Comment by dwdixon** [comment]
Thanks, at least on Ubuntu 18.04 there's no simple way to install libreadline8, AFAIK.  I ended up just commenting out like so (below) for a quick workaround and then re-running `./autogen.sh` then `./configure` went off without a hitch...of course checking out a commit prior to [c18f3d2](https://github.com/nhorman/dropwatch/commit/c18f3d25a94eb72145c663797794d2697a226594) would be a cleaner way to go...

```
# Fallback on using -lreadline as readline.pc is only available since version 8.0
PKG_CHECK_MODULES([READLINE], [readline], [], [READLINE_LIBS=-lreadline])
#PKG_CHECK_MODULES([READLINE], [readline], [], [AC_MSG_ERROR([libreadline is required])])
```

For folks on Ubuntu this is roughly the command people need to run prior to pull in dependancies prior building given they've made the change I mentioned here or checked out a commit prior to [c18f3d2](https://github.com/nhorman/dropwatch/commit/c18f3d25a94eb72145c663797794d2697a226594):

`sudo apt-get install libnl-3-dev libnl-genl-3-dev libreadline-dev libpcap-dev binutils-dev`

**Comment by nhorman** [comment]
Please don't just comment things out of the configure script without understanding what they do. just commenting out PKG_CHECK_MODULES is going to break, because commit c18fd32 does more than that, it removed the static addition of -I /usr/include/readline.h in the Makefile build rule, and -Lreadline in the link rule.  As such the package install set you reference won't help because you haven't included those compiler/linker flags, and you will get exactly the issue described here.

**Comment by dwdixon** [comment]
Thanks this makes a lot of sense, I very quickly did the above in my last comment...so yeah YMMV, probably not ideal.  

FWIW, and I may be doing something wrong but I cloned the repo and checked out the commit immediately prior to c18fd32 (a1aafca) via `git checkout a1aafca` but then I hit this when trying to run `./autogen.sh`

```
dropwatch$ ./autogen.sh
+ mkdir -p m4
+ autoreconf -fv --install
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:7: warning: macro 'AM_PROG_LIBTOOL' not found in library
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:7: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

It would be really nice for Canonical to update 18.04 to the latst readline package, hopefully that happens and makes everyone's lives a lot easier with this.
